using System.Collections;
using System.Collections.Specialized;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using MyWorkDay.Core;

namespace MyWorkDay.Controls;

/// <summary>A real ring/donut chart (matching the Python build's CSS conic-gradient donut) -
/// each DonutSlice becomes a proportional wedge, drawn as a Path with matching outer/inner
/// arcs. There's no built-in WPF pie/donut control, so the geometry is generated by hand here;
/// see BuildSlices for the angle math.</summary>
public partial class DonutChart : UserControl
{
    // Same palette the Python build cycled through for its donut/legend colors.
    public static readonly Color[] Palette =
    {
        Color.FromRgb(0x25, 0x63, 0xEB), Color.FromRgb(0x7C, 0x3A, 0xED), Color.FromRgb(0x16, 0xA3, 0x4A),
        Color.FromRgb(0xEA, 0x58, 0x0C), Color.FromRgb(0xDC, 0x26, 0x26), Color.FromRgb(0x08, 0x91, 0xB2),
        Color.FromRgb(0xCA, 0x8A, 0x04), Color.FromRgb(0xBE, 0x18, 0x5D),
    };

    public static readonly DependencyProperty SlicesProperty = DependencyProperty.Register(
        nameof(Slices), typeof(IEnumerable), typeof(DonutChart),
        new PropertyMetadata(null, OnSlicesChanged));

    public IEnumerable? Slices
    {
        get => (IEnumerable?)GetValue(SlicesProperty);
        set => SetValue(SlicesProperty, value);
    }

    public static readonly DependencyProperty TotalMinutesProperty = DependencyProperty.Register(
        nameof(TotalMinutes), typeof(int), typeof(DonutChart), new PropertyMetadata(0, OnTotalChanged));

    public int TotalMinutes
    {
        get => (int)GetValue(TotalMinutesProperty);
        set => SetValue(TotalMinutesProperty, value);
    }

    public DonutChart()
    {
        InitializeComponent();
    }

    private static void OnSlicesChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        var chart = (DonutChart)d;
        if (e.OldValue is INotifyCollectionChanged oldIncc) oldIncc.CollectionChanged -= chart.OnCollectionChanged;
        if (e.NewValue is INotifyCollectionChanged newIncc) newIncc.CollectionChanged += chart.OnCollectionChanged;
        chart.Redraw();
    }

    private static void OnTotalChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) => ((DonutChart)d).UpdateTotalText();

    private void OnCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e) => Redraw();

    private void UpdateTotalText() => TotalText.Text = DashboardStats.FormatMinutes(TotalMinutes);

    private void Redraw()
    {
        SliceCanvas.Children.Clear();
        UpdateTotalText();

        var slices = (Slices?.Cast<DonutSlice>() ?? Enumerable.Empty<DonutSlice>())
            .Where(s => s.Minutes > 0).ToList();
        var total = slices.Sum(s => s.Minutes);

        const double size = 132, outerR = 66, innerR = 37;
        var center = new Point(size / 2, size / 2);

        if (total <= 0 || slices.Count == 0)
        {
            // Empty state: a flat gray ring, same idea as the Python build's
            // "#e5e7eb" fallback background when the donut has nothing to show.
            SliceCanvas.Children.Add(BuildRingSlice(center, outerR, innerR, 0, 360, Color.FromRgb(0xE5, 0xE7, 0xEB)));
            return;
        }

        double cumulative = 0;
        for (var i = 0; i < slices.Count; i++)
        {
            var fraction = (double)slices[i].Minutes / total;
            var sweep = fraction * 360.0;
            var color = Palette[i % Palette.Length];
            SliceCanvas.Children.Add(BuildRingSlice(center, outerR, innerR, cumulative, sweep, color));
            cumulative += sweep;
        }
    }

    private static System.Windows.Shapes.Path BuildRingSlice(Point center, double outerR, double innerR, double startDeg, double sweepDeg, Color color)
    {
        // A full circle (sweep >= 360) degenerates the arc math below (start == end point), so
        // draw it as two 180-degree wedges instead - the one real edge case in this geometry.
        if (sweepDeg >= 359.999)
        {
            var g1 = BuildWedgeGeometry(center, outerR, innerR, 0, 180);
            var g2 = BuildWedgeGeometry(center, outerR, innerR, 180, 180);
            var group = new GeometryGroup();
            group.Children.Add(g1);
            group.Children.Add(g2);
            return new System.Windows.Shapes.Path { Data = group, Fill = new SolidColorBrush(color) };
        }

        var geometry = BuildWedgeGeometry(center, outerR, innerR, startDeg, sweepDeg);
        return new System.Windows.Shapes.Path
        {
            Data = geometry,
            Fill = new SolidColorBrush(color),
            Stroke = Brushes.White,
            StrokeThickness = 1.5,
        };
    }

    private static PathGeometry BuildWedgeGeometry(Point center, double outerR, double innerR, double startDeg, double sweepDeg)
    {
        var endDeg = startDeg + sweepDeg;
        var isLargeArc = sweepDeg > 180;

        var outerStart = PointOnCircle(center, outerR, startDeg);
        var outerEnd = PointOnCircle(center, outerR, endDeg);
        var innerEnd = PointOnCircle(center, innerR, endDeg);
        var innerStart = PointOnCircle(center, innerR, startDeg);

        var figure = new PathFigure { StartPoint = outerStart, IsClosed = true };
        figure.Segments.Add(new ArcSegment(outerEnd, new Size(outerR, outerR), 0, isLargeArc, SweepDirection.Clockwise, true));
        figure.Segments.Add(new LineSegment(innerEnd, true));
        figure.Segments.Add(new ArcSegment(innerStart, new Size(innerR, innerR), 0, isLargeArc, SweepDirection.Counterclockwise, true));
        figure.Segments.Add(new LineSegment(outerStart, true));

        var geometry = new PathGeometry();
        geometry.Figures.Add(figure);
        return geometry;
    }

    /// <summary>0 degrees = straight up, increasing clockwise - matches a CSS conic-gradient's
    /// own angle convention, which is what the Python build's donut used.</summary>
    private static Point PointOnCircle(Point center, double radius, double angleDeg)
    {
        var rad = (angleDeg - 90) * Math.PI / 180.0;
        return new Point(center.X + radius * Math.Cos(rad), center.Y + radius * Math.Sin(rad));
    }
}
